### PR TITLE
Enactment states column

### PR DESCRIPTION
**Pull request by upalatucci**
Change the column title from 'Node network state' to 'Enactment states' as the filter in the toolbar is called this way.

Screenshot from 2023-10-24 13-02-17

### CODE REVIEW

**Review by hstastna — COMMENTED** [review]
Hi @upalatucci , I can see in the screenshot the filter in the toolbar is called "Enactment state". However you used plural for the new column title. Maybe we could make it consistent in the both places? It would look better, it is a little change. Also I can see the original column name also uses singular, not plural. So maybe singular is the right form of the word "state"...

**Comment by upalatucci** [comment]
Yeah, it's challenging to choose what to put here. I put plural in the column as for each column we have multiple enactments but in the filter, it does make sense to use singular as we use singular here every time.

**Comment by hstastna** [comment]
Hmm, now it makes more sense to me to use plural in both places. Because when filtering, you also can filter more states, and the result of filtering can also be more states.
Another option to solve this is to ask someone from UX or doc team, to make sure about the correct form/forms used in both places.

**Comment by upalatucci** [comment]
let's use the plural for both. If someone complain, we can change that

**Review by hstastna — APPROVED** [review]

**Pull request merged**
